config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  root "events#index"
  
  resources :events do
    resources :reviews, only: [:new, :create]
  end
  
  get '/skills/searchskill',  to: 'skills#search_skill'
  resources :skills do
    collection do
      get 'search'
    end
  end
  
  get '/reviews/searchreview',  to: 'reviews#search_review'
  resources :reviews, only: [:index] do
    collection do
      get 'search'
    end
  end
  resources :reviews, only: [:show, :edit, :update, :destroy]

end

app/models/skill.rb
class Skill < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category
  belongs_to :genre
  belongs_to :user

  has_one_attached :video
  has_one_attached :image

  with_options presence: true do
    validates :drill_name, length: { maximum: 20 }
    validates :info, length: { maximum: 1000 }
    validates :category_id
    validates :genre_id
  end

  validates :image, file_content_type: { allow: ['image/jpeg', 'image/jpg', 'image/png', 'image/bmp', 'image/gif'] }

  validates :video, file_content_type: { allow: ['video/mp4', 'video/mov', 'video/quicktime'] }

  URL_REGEX = /\A#{URI::DEFAULT_PARSER.make_regexp(%w[http https])}\z/.freeze
  validates :skill_url, format: { with: URL_REGEX, message: 'enter the URL', allow_blank: true }
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :searching_skills, only: [:index, :search_skill]

  def index
    @news = Skill.limit(10).order(created_at: :desc)
    @skills = Skill.includes(:user).order(created_at: :desc)
  end

  def new
    @skill = Skill.new
  end

  def create
    @skill = Skill.new(skill_params)
    if @skill.save
      redirect_to skills_path
    else
      render :new
    end
  end

  def show
    @skill = Skill.find(params[:id])
  end

  def edit
    @skill = Skill.find(params[:id])
  end

  def update
    @skill = Skill.find(params[:id])
    if @skill.update(skill_params)
      redirect_to skill_path
    else
      render :edit
    end
  end

  def destroy
    @skill = Skill.find(params[:id])
    if @skill.destroy
      redirect_to skills_path
    else
      render :show
    end
  end

  def search
    return nil if params[:keyword] == ''
  end

  def search_skill
    @results = @p.result
  end

  private

  def skill_params
    params.require(:skill).permit(:drill_name, :info, :category_id, :genre_id, :video, :image, :skill_url).merge(user_id: current_user.id)
  end

  def searching_skills
    @p = Skill.ransack(params[:q])
  end
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/skills/edit.html.erb
<%= render "shared/skills-second-header"%>

<div class="skill-body">

  <%= form_with model: @skill, url: skill_path, class:'form-wrap', local: true do |form| %>
    <%= render 'shared/error_messages', model: form.object %> 

    <h1 class="new-skill-title">
      編集
    </h1>

    <div class="form-body">

      <div class="form-box">
        <div class="form-title">
          <%= form.label :drill_name, "タイトル"%>
        </div>
        <div class='form'>
          <div class="side-form">
          </div>
          <div class="main-form">
            <%= form.text_field :drill_name, class:"input-form" %>
          </div>
        </div>
      </div>

      <div class="form-box">
        <div class="form-title">
          <%= form.label :genre_id, "ジャンル"%>
        </div>
        <div class="form">
          <div class="side-form">
          </div>
          <div class="main-form">
            <%= form.collection_select(:genre_id, Genre.all, :id, :name, {include_blank:"選択して下さい"}, {class:"select"}) %>
          </div>
        </div>
      </div>

      <div class="form-box">
        <div class="form-title">
          <%= form.label :category_id, "対象ポジション"%>
        </div>
        <div class="form">
          <div class="side-form"></div>
          <div class="main-form">
            <%= form.collection_select(:category_id, Category.all, :id, :name, {include_blank:"選択して下さい"}, {class:"select"}) %>
          </div>
        </div>
      </div>
      
      <div class="form-box">
        <div class="form-title">
          <%= form.label :info, "解説"%>
        </div>
        <div class="form">
          <div class="side-form"></div>
          <div class="skill-info-form">
              <%= form.text_area :info, class:"input-form", rows: "7", maxlength:"1000" %>
          </div>
        </div>
      </div>

      <div class="form-box">
        <div class="form-title">
          <%= form.label :image, "画像 (jpg, png, gif)"%>
        </div>
        <div class="media-form">
            <%= form.file_field :image %>
        </div>
      </div>


      <div class="form-box">
        <div class="form-title">
          <%= form.label :video, "動画 (mp4, mov)"%>
        </div>
        <div class="media-form">
            <%= form.file_field :video %>
        </div>
      </div>

      <div class="form-box">
        <div class="form-title">
          <%= form.label :skill_url, "参考動画URL(You tubeなど)"%>
        </div>
        <div class='media-form'>
            <%= form.text_field :skill_url, class:"input-form", placeholder:" https://www.youtube.com/watch?v=○○○○○○" %>
        </div>
      </div>
    
      <div class="submit-post">
        <%= form.submit '登録' ,class:"submit-btn" %>
      </div>
      <div>
        <%=link_to 'もどる', skills_path, class:"back-btn" %>
      </div>

    </div>
  <% end %>


</div>

app/views/skills/index.html.erb
<%= render "shared/skills-header" %>

<div class="skills-body">

  <div class="skills-main">

    <div class="search-skill-main">
      <div class="search-skill-title">検索フォーム
      </div>
      <div class="search-skill-form">
        <%= search_form_for @p, url: skills_searchskill_path do |form| %>

          <div class="skill-form">
            <%= form.label :drill_name, "タイトル" %>
            <%= form.search_field :drill_name_cont, class:"search-input" %>
          </div>

          <div class="skill-form">
            <%= form.label :genre_id, "ジャンル"%>
            <%= form.collection_select :genre_id_eq, Genre.all, :id, :name, {include_blank: '指定なし'}, {class:"search-select"} %>
          </div>

          <div class="skill-form">
            <%= form.label :category_id, "対象ポジション"%>
            <%= form.collection_select :category_id_eq, Category.all, :id, :name, {include_blank: '指定なし'}, {class:"search-select"} %>
          </div>
          <div class="search-form-btn">
            <%= form.submit "検索" ,class:"search-btn"%>
          </div>
        <% end %>
      </div>
    </div>

      <%= link_to '新規登録', new_skill_path, class:"skill-index-btn" %>

    <div class="new-list">
      <div class="new-list-title">新着リスト</div>
      <div class="new-list-main">
        <% @news.each do |skill| %>
            <ul class="skill-item">
              <%= link_to skill_path(skill.id), method: :get do %>
                <%= skill.drill_name %>
              <% end %>
            </ul>
        <% end %>
      </div>
    </div>

  </div>

</div>

<%= render "shared/footer" %>

app/views/skills/new.html.erb
<%= render "shared/skills-second-header"%>

<div class="skill-body">

  <%= form_with model: @skill, url: skills_path, class:'form-wrap', local: true do |form| %>
    <%= render 'shared/error_messages', model: form.object %> 

    <h1 class="new-skill-title">
      新規登録
    </h1>

    <div class='form-body'>

      <div class="form-box">
        <div class="form-title">
          <%= form.label :drill_name, "タイトル"%>
        </div>
        <div class='form'>
          <div class="side-form">
          </div>
          <div class="main-form">
            <%= form.text_field :drill_name, class:"input-form" %>
          </div>
        </div>
      </div>

      <div class="form-box">
        <div class="form-title">
          <%= form.label :genre_id, "ジャンル"%>
        </div>
        <div class="form">
          <div class="side-form">
          </div>
          <div class="main-form">
            <%= form.collection_select(:genre_id, Genre.all, :id, :name, {include_blank:"選択して下さい"}, {class:"select"}) %>
          </div>
        </div>
      </div>

      <div class="form-box">
        <div class="form-title">
          <%= form.label :category_id, "対象ポジション"%>
        </div>
        <div class="form">
          <div class="side-form"></div>
          <div class="main-form">
            <%= form.collection_select(:category_id, Category.all, :id, :name, {include_blank:"選択して下さい"}, {class:"select"}) %>
          </div>
        </div>
      </div>
      
      <div class="form-box">
        <div class="form-title">
          <%= form.label :info, "解説"%>
        </div>
        <div class="form">
          <div class="skill-info-form">
            <%= form.text_area :info, class:"input-form", rows: "7", maxlength:"1000" %>
          </div>
        </div>
      </div>

      <div class="form-box">
        <div class="form-title">
          <%= form.label :image, "画像 (jpg, png, gif)"%>
        </div>
        <div class="media-form">
            <%= form.file_field :image %>
        </div>
      </div>

      <div class="form-box">
        <div class="form-title">
          <%= form.label :video, "動画 (mp4, mov)"%>
        </div>
        <div class="media-form">
            <%= form.file_field :video %>
        </div>
      </div>

      <div class="form-box">
        <div class="form-title">
          <%= form.label :skill_url, "参考動画URL(You tubeなど)"%>
        </div>
        <div class='media-form'>
            <%= form.text_field :skill_url, class:"input-form", placeholder:" https://www.youtube.com/watch?v=○○○○○○" %>
        </div>
      </div>
    
      <div class="submit-post">
        <%= form.submit '登録' ,class:"submit-btn" %>
      </div>
      <div>
        <%=link_to 'もどる', skills_path, class:"back-btn" %>
      </div>

    </div>
  <% end %>


</div>

app/views/skills/search_skill.html.erb
<%= render "shared/skills-second-header"%>

<div class="skills-body">

  <div class="skills-search-main">
    <div class="review-search-title">
      検索結果
    </div>
    <div class='skills-search-body'>
      <% if @results.length != 0 %>
        <% @results.each do |skill| %>
          <li class='skills-search-result'>
            <% if skill %>
              <%= link_to skill_path(skill.id) do %>
                <span class="skill-item"><%= skill.drill_name %></span>
              <% end %>
            <% end %>
          </li>
        <% end %>
      <% else %>
        該当する項目がありません
      <% end %>
    </div>
    <div class="search-end">
      <%= link_to "もどる", skills_path %>
    </div>
  </div>
</div>

<%= render "shared/footer" %>

app/views/skills/show.html.erb
<%= render "shared/skills-second-header" %>

<div class="skill-body">

  <div class="skill-info"> 

    <div class="skill-info-main">
      <div class="skill-info-box">
        <div class="info-left-box">
        名前
        </div>
        <div class="info-center-box">
        ：
        </div>
        <div class="info-right-box">
          <%= @skill.drill_name %>
        </div>
      </div>

      <div class="skill-info-box">
        <div class="info-left-box">
        ジャンル
        </div>
        <div class="info-center-box">
        ：
        </div>
        <div class="info-right-box">
          <%= @skill.genre.name %>
        </div>
      </div>

      <div class="skill-info-box">
        <div class="info-left-box">
        対象
        </div>
        <div class="info-center-box">
        ：
        </div>
        <div class="info-right-box">
          <%= @skill.category.name %>
        </div>
      </div>

      <div class="skill-explain">
        <div class="explain-title">
          解説
        </div>
        <span class="explain-main"><%= @skill.info %></span>
      </div>

      <% if @skill.skill_url? %>
        <div class="skill-explain">
          <div class="explain-title">
            参考動画
          </div>
          <span class="explain-main">          <%= link_to @skill.skill_url, @skill.skill_url %></span>
        </div>
      <% end %>

    </div>

    <div class="media-viewer">
      <% if @skill.image.attached? && @skill.video.attached? %>
        <img src="<%= rails_blob_path(@skill.image) %>", class="image-viewer" >
        <%= video_tag rails_blob_path(@skill.video, disposition: "attachment"),class: "video-player", controls: :true %>
      <% elsif @skill.image.attached? %>
        <img src="<%= rails_blob_path(@skill.image) %>", class="image-viewer" >
      <% elsif @skill.video.attached?%>
        <%= video_tag rails_blob_path(@skill.video, disposition: "attachment"),class: "video-player", controls: :true %>
      <% else %>
        <div class="no-media">
          参考動画像なし
        </div>
      <% end %>

    </div>

  </div>

    <% if user_signed_in? %>
      <div class="edit-destroy">
        <%= link_to '編集', edit_skill_path(@skill.id), class:"edit-btn" %>
        <%= link_to '削除', skill_path(@skill.id), method: :delete, class: "destroy-btn" %>
      </div>
    <% end %>

    <div>
      <%=link_to 'もどる', skills_path, class:"back-btn" %>
    </div>

</div>
<%= render "shared/footer" %>