config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  root "events#index"
  
  resources :events do
    resources :reviews, only: [:new, :create]
  end
  
  get '/skills/searchskill',  to: 'skills#search_skill'
  resources :skills do
    collection do
      get 'search'
    end
  end
  
  get '/reviews/searchreview',  to: 'reviews#search_review'
  resources :reviews, only: [:index] do
    collection do
      get 'search'
    end
  end
  resources :reviews, only: [:show, :edit, :update, :destroy]

end

app/models/event.rb
class Event < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :title
  belongs_to :meeting_time

  belongs_to :user
  has_one :review, dependent: :destroy

  with_options presence: true do
    validates :title_id
    validates :start_time, uniqueness: true
    validates :meeting_time_id
  end

  validates :info, length: { maximum: 1000 }
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :show, :edit, :update, :destroy]

  def index
    @events = Event.includes(:user)
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    load_event
  end

  def edit
    load_event
  end

  def update
    load_event
    if @event.update(event_params)
      redirect_to event_path
    else
      render :edit
    end
  end

  def destroy
    load_event
    if @event.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  private

  def event_params
    params.require(:event).permit(:title_id, :start_time, :meeting_time_id, :info).merge(user_id: current_user.id)
  end

  def load_event
    @event = Event.find(params[:id])
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/edit.html.erb
<%= render "shared/second-header"%>

<div class="event-day">

  <h2 class="event-day-title">活動日編集</h2>

  <div class="event-day-main">
      <%= form_with model: @event, local: true do |f| %>
        <%= render 'shared/error_messages', model: f.object %> 

          <div class="weight-bold-text">タイトル</div>
          <div class="form">
            <div class="side-form">
            </div>
            <div class="main-form">
            <%= f.collection_select(:title_id, Title.all, :id, :name, {include_blank:"選択して下さい"}, {class:"select-box", id:"event-title"}) %>
            </div>
          </div>

          <div class="weight-bold-text">日時</div>
          <div class="form">
            <div class="side-form">
            </div>
            <div class="main-form">
            <%= f.date_select :start_time %>
            </div>
          </div>

          <div class="weight-bold-text">集合時間</div>
          <div class="form">
            <div class="side-form">
            </div>
            <div class="main-form">
            <%= f.collection_select(:meeting_time_id, MeetingTime.all, :id, :name, {include_blank:"選択して下さい"}, {class:"select-box", id:"event-meeting-time"}) %>
            </div>
          </div>

          <div class="weight-bold-text">詳細情報</div>
          <div class="form">
            <div class="side-form">
            </div>
            <div class="main-form">
            <%= f.text_area :info ,class: 'day-info', placeholder:" 練習内容の説明や活動場所など", rows:'4'%>
            </div>
          </div>
          
          <div class="link-btn-contents">
            <div class="send-link">
              <%= f.submit "編集する" ,class:"create-btn" %>
            </div>
            <div class="back-link">
              <%=link_to 'もどる', root_path, class:"back-btn" %>
            </div>
          </div>

      <% end %>
  </div>
</div>

app/views/events/index.html.erb
<%= render "shared/header" %>
<div class="event-body">
  <div class="event-main">

    <div class="left-side">
        <div class="new-day">
          <%= link_to '活動日登録', new_event_path, class:"index-btn" %>
        </div>
        <div class="match-review">

          <%= link_to '試合レビュー', reviews_path, class:"index-btn" %>
        </div>

        <div class="strategy-dictionary">
          <%= link_to '解説辞典', skills_path, class:"index-btn" %>
        </div>
    </div>

    <div class="main-calendar">
      <div class="calendar-head">
        <%= link_to 'this month', '/', class: "this-month" %>
      </div>
      <div class="calendar-part">
        <%= month_calendar events: @events do |date, events| %>
          <%= date.day %>

          <% events.each do |event| %>
            <%= link_to event_path(event.id) do %>
              <div class="day_title_name">
                <%= event.title.name %>
              </div>
              <div class="day_meeting_time">
                <% if event.meeting_time.id != 1 %>
                  <%= event.meeting_time.name %>〜
                <% end %>
              </div>
            <% end %>
          <% end %>

        <% end %>
      </div>
    </div>

  </div>
</div>

<%= render "shared/footer" %>

app/views/events/new.html.erb
<%= render "shared/second-header"%>

<div class="event-day">

  <h2 class="event-day-title">活動日登録</h2>

  <div class="event-day-main">
      <%= form_with model: @event, local: true do |f| %>
        <%= render 'shared/error_messages', model: f.object %> 

          <div class="weight-bold-text">タイトル</div>
          <div class="form">
            <div class="side-form">
            </div>
            <div class="main-form">
            <%= f.collection_select(:title_id, Title.all, :id, :name, {include_blank:"選択して下さい"}, {class:"select-box", id:"event-title"}) %>
            </div>
          </div>

          <div class="weight-bold-text">日時</div>
          <div class="form">
            <div class="side-form">
            </div>
            <div class="main-form">
            <%= f.date_select :start_time %>
            </div>
          </div>

          <div class="weight-bold-text">集合時間</div>
          <div class="form">
            <div class="side-form">
            </div>
            <div class="main-form">
              <%= f.collection_select(:meeting_time_id, MeetingTime.all, :id, :name, {include_blank:"選択して下さい"}, {class:"select-box", id:"event-meeting-time"}) %>
            </div>
          </div>

          <div class="weight-bold-text">詳細情報</div>
          <div class="form">
            <div class="main-form">
              <%= f.text_area :info ,class: 'day-info', placeholder:" 練習内容の説明や活動場所など", rows:'4'%>
            </div>
          </div>
          
          <div class="link-btn-contents">
            <div class="send-link">
              <%= f.submit "登録する" ,class:"create-btn" %>
            </div>
            <div class="back-link">
              <%=link_to 'もどる', root_path, class:"back-btn" %>
            </div>
          </div>

      <% end %>
  </div>
</div>

app/views/events/show.html.erb
<%= render "shared/second-header"%>

<div class="event-show">


  <div class="event-day-contents">

  <div class="event-day-title"><%= @event.start_time %></div>
    <div class="event-info-body">

      <div class="event-info-box">
        <div class="event-left-box">
        タイトル
        </div>
        <div class="event-center-box">
        ：
        </div>
        <div class="event-right-box">
          <%= @event.title.name %>
        </div>
      </div>

        <% if @event.meeting_time_id != 1 %>

          <div class="event-info-box">
            <div class="event-left-box">
              集合時間
            </div>
            <div class="event-center-box">
              ：
            </div>
            <div class="event-right-box">
              <%= @event.meeting_time.name %>〜
            </div>
          </div>
        
        <% end %>

        <div class="event-explain">
          <div class="info-title">
            詳細情報
          </div>
          <% if @event.info != "" %>
            <div class="explain-main">
              <%= @event.info %>
            </div>
          <% else %>
            <%# 空白の場合 %>
              <div class="off-explain-main">特になし
              </div>
            <%# 空白の場合 %>
          <% end %>
        </div>
    </div>

    <% if user_signed_in? %>
      <%# 試合の場合はレビュー作成へ %>
        <% if ( @event.title_id == 3 ) || ( @event.title_id == 4 )%>
          <%= link_to '試合レビュー', new_event_review_path(@event.id), class:"match-review-btn" %>
        <% end %>
      <%# 試合の場合はレビュー作成へ %>
      <div class="edit-destroy">
        <%= link_to '編集', edit_event_path, class: "edit-btn" %>
        <%= link_to '削除', event_path(@event.id), method: :delete, class: "destroy-btn" %>
      </div>
    <% end %>

    <div>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>


  </div>
</div>