config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  root "events#index"
  
  resources :events do
    resources :reviews, only: [:new, :create]
  end
  
  get '/skills/searchskill',  to: 'skills#search_skill'
  resources :skills do
    collection do
      get 'search'
    end
  end
  
  get '/reviews/searchreview',  to: 'reviews#search_review'
  resources :reviews, only: [:index] do
    collection do
      get 'search'
    end
  end
  resources :reviews, only: [:show, :edit, :update, :destroy]

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!
  before_action :no_match_block, only: [:new, :create]
  before_action :review_double_block, only: [:new, :create]
  before_action :searching_reviews, only: [:index, :search_review]

  def index
    @news = Review.order(match_date: :desc).limit(10)
    @reviews = Review.includes(:user).order(match_date: :desc)
  end

  def new
    @review = Review.new
    @event = Event.find(params[:event_id])
  end

  def create
    @review = Review.new(review_params)
    if @review.valid?
      @review.save
      redirect_to reviews_path
    else
      render :new
    end
  end

  def show
    load_review
  end

  def edit
    load_review
  end

  def update
    load_review
    if @review.update(update_params)
      redirect_to review_path
    else
      render :edit
    end
  end

  def destroy
    load_review
    if @review.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  def search
    return nil if params[:keyword] == ''
  end

  def search_review
    @results = @p.result
  end

  private

  def review_params
    params.require(:review).permit(:match_genre_id, :opponent_team, :comment, :match_url, :match_date).merge(user_id: current_user.id, event_id: params[:event_id])
  end

  def update_params
    params.require(:review).permit(:match_genre_id, :opponent_team, :comment, :match_url, :match_date)
  end

  def load_review
    @review = Review.find(params[:id])
  end

  def no_match_block
    @event = Event.find(params[:event_id])
    if @event.title_id == 3
    elsif @event.title_id == 4
    else
      redirect_to root_path
    end
  end

  def review_double_block
    redirect_to reviews_path unless @event.review.nil?
  end

  def searching_reviews
    @p = Review.ransack(params[:q])
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/edit.html.erb
<%= render "shared/reviews-second-header"%>

<div class="review-new">
  <%= form_with model: @review, url: review_path, class:'form-wrap', local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %> 

    <h1 class="review-title">レビュー編集</h1>


      <div class="form-box">
        <div class="form-title">
          <%= f.label :match, "試合日"%>
        </div>
        <div class='review-f'>
          <div class="side-form">
          </div>
          <div class="main-form">
            <div class='date-field'>
              <%= raw sprintf(f.date_select(:match_date, class:'select-',use_month_numbers: true,prompt:'--',start_year: 2019,end_year: (Time.now.year + 2),date_separator: '%s'),
              "年", "月") + "日" %>
            </div>
          </div>
        </div>
      </div>

      
      <div class="form-box">
        <div class="form-title">
          <%= f.label :match_genre_id, "試合ジャンル"%>
        </div>
        <div class='form'>
          <div class="side-form">
          </div>
          <div class="main-form">
            <%= f.collection_select(:match_genre_id, MatchGenre.all, :id, :name, {include_blank:"選択して下さい"}, {class:"select", id:"match_genre_box"}) %>
          </div>
        </div>
      </div>

      <div class="form-box">
        <div class="form-title">
          <%= f.label :opponent_team, "対戦相手"%>
        </div>
        <div class='form'>
          <div class="side-form">
          </div>
          <div class="main-form">
            <%= f.text_field :opponent_team, class:"input-form" %>
          </div>
        </div>
      </div>


      <div class="form-box">
        <div class="form-title">
          <%= f.label :comment, "レビュー本文", maxlength:"1000" %>
        </div>
        <div class="form">
          <%= f.text_area :comment, class:"input-form", placeholder:"総括", rows:'8'%>
        </div>
      </div>

      <div class="form-box">
        <div class="form-title">
          <%= f.label :match_url, "試合動画URL(You tubeなど)"%>
        </div>
        <div class='form'>
            <%= f.text_area :match_url, class:"input-form", placeholder:" https://www.youtube.com/watch?v=○○○○○○" %>
        </div>
      </div>
      
      <div class="submit-post">
        <%= f.submit '編集' ,class:"submit-btn" %>
      </div>
      <div>
        <%=link_to 'もどる', reviews_path, class:"back-btn" %>
      </div>

  <% end %>

</div>

app/views/reviews/index.html.erb
<%= render "shared/reviews-header" %>


<div class="review-index">

  <div class="review-main">

    <div class="new-reviews-list">
      <div class="new-list-title">
        新着リスト
      </div>

      <div class="new-reviews-main">
        <% @news.each do |review| %>
          <ul class="review-item">
            <%= link_to review_path(review.id) ,method: :get do%>
            <%= review.match_genre.name %>  vs <%= review.opponent_team%>
            <% end %>
          </ul>
        <% end %>
      </div>
    </div>


  <div class="search-reviews-main">
    <div class="search-skill-title">
    検索フォーム
    </div>

    <div class="search-skill-form">
        <%= search_form_for @p, url: reviews_searchreview_path do |form| %>

          <div class="skill-form">
            <%= form.label :opponent_team, "対戦相手" %>
            <%= form.search_field :opponent_team_cont, class:"search-input" %>
          </div>

          <div class="skill-form">
            <%= form.label :match_genre_id, "試合ジャンル"%>
            <%= form.collection_select :match_genre_id_eq, MatchGenre.all, :id, :name, 
            {include_blank: '指定なし'}, 
            {class:"search-select"} %>
          </div>
          <div class="search-form-btn">
            <%= form.submit "検索" ,class:"search-btn"%>
          </div>
        <% end %>
    </div>
    
  </div>

  </div>
</div>

<%= render "shared/footer" %>

app/views/reviews/new.html.erb
<%= render "shared/reviews-second-header"%>

<div class="review-new">
  <%= form_with model: @review, url: event_reviews_path, class:'form-wrap', local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %> 

    <h1 class="new-review-title">新規試合レビュー登録</h1>


      <div class="form-box">
        <div class="form-title">
          <%= f.label :match, "試合日"%>
        </div>
        <div class='review-f'>
          <div class="side-form">
          </div>
          <div class="main-form">
            <div class='date-field'>
              <%= raw sprintf(f.date_select(:match_date, class:'select-',use_month_numbers: true,prompt:'--',start_year: 2019,end_year: (Time.now.year + 2),date_separator: '%s'),
              "年", "月") + "日" %>
            </div>
          </div>
        </div>
      </div>

      
      <div class="form-box">
        <div class="form-title">
          <%= f.label :match_genre_id, "試合ジャンル"%>
        </div>
        <div class='form'>
          <div class="side-form">
          </div>
          <div class="main-form">
            <%= f.collection_select(:match_genre_id, MatchGenre.all, :id, :name, {include_blank:"選択して下さい"}, {class:"select", id:"match_genre_box"}) %>
          </div>
        </div>
      </div>

      <div class="form-box">
        <div class="form-title">
          <%= f.label :opponent_team, "対戦相手"%>
        </div>
        <div class='form'>
          <div class="side-form">
          </div>
          <div class="main-form">
            <%= f.text_field :opponent_team, placeholder:"高校名", class:"input-form" %>
          </div>
        </div>
      </div>


      <div class="form-box">
        <div class="form-title">
          <%= f.label :comment, "レビュー本文", maxlength:"1000" %>
        </div>
        <div class="form">
          <%= f.text_area :comment, class:"input-form", placeholder:"試合コメントなど(1000字以内)", rows:'8'%>
        </div>
      </div>

      <div class="form-box">
        <div class="form-title">
          <%= f.label :match_url, "試合動画URL(You tubeなど)"%>
        </div>
        <div class='form'>
            <%= f.text_area :match_url, class:"input-form", placeholder:" https://www.youtube.com/watch?v=○○○○○○" %>
        </div>
      </div>


      <div class="submit-post">
        <%= f.submit '登録' ,class:"submit-btn" %>
      </div>
      <div>
        <%=link_to 'もどる', event_path(@event.id), class:"back-btn" %>
      </div>

  <% end %>

</div>

app/views/reviews/search_review.html.erb
<%= render "shared/reviews-second-header"%>

<div class="review-index">

  <div class="reviews-search-body">
    <div class="review-search-title">
      検索結果
    </div>
    <div class="review-search-main">
      <% if @results.length != 0 %>
        <% @results.each do |review| %>
          <li class="reviews-search-result">
            <% if review %>
              <%= link_to review_path(review.id) do %>
                <span><%= review.match_date%></span>
                <span><%= review.match_genre.name %></span>
                <span><%= review.opponent_team%></span>
              <% end %>
            <% end %>
          </li>
        <% end %>
      <% else %>
      該当する項目がありません
      <% end %>
    </div>
    <div class="search-end">
      <%= link_to "もどる", reviews_path, class:'back-btn' %>
    </div>
  </div>
</div>

<%= render "shared/footer" %>

app/views/reviews/show.html.erb
<%= render "shared/reviews-second-header"%>

<div class="review-show">

  <div class="review-show-body">



    <div class="review-show-main">

      <div class="review-info-box">
        <div class="review-left-box">
          日付
        </div>
        <div class="review-center-box">
          ：
        </div>
        <div class="review-right-box">
          <%= @review.match_date %>
        </div>
      </div>

      <div class="review-info-box">
        <div class="review-left-box">
          対戦相手
        </div>
        <div class="review-center-box">
          ：
        </div>
        <div class="review-right-box">
          <%= @review.opponent_team %>
        </div>
      </div>

      <div class="review-info-box">
        <div class="review-left-box">
          試合形式
        </div>
        <div class="review-center-box">
          ：
        </div>
        <div class="review-right-box">
          <%= @review.match_genre.name %>
        </div>
      </div>

      <div class="review-comment">
        <div class="review-comment-title">
          コメント
        </div>
        <div class="review-comment-main"><%= @review.comment %>
        </div>
      </div>

      <% if @review.match_url != "" %>
        <div class="match-url-box">
          <div class="match-url-title">
            試合ビデオURL
          </div>
          <div class="match-url-main">
            <%= link_to  @review.match_url, @review.match_url, class:"url" %>
          </div>
        </div>
      <% end %>

    </div>

    <% if user_signed_in? %>
      <div class="edit-destroy">
        <%= link_to '編集', edit_review_path, class: "edit-btn" %>
        <%= link_to '削除', review_path(@review.id), method: :delete, class: "destroy-btn" %>
      </div>
    <% end %>
    
    <%= link_to 'もどる', reviews_path%>

  </div>
  
</div>

<%= render "shared/footer" %>